server:
  port: 6061
     
db:
 active:
   ipaddress: XXXX
 standby:
   ipaddress: XXXX  
 database: XXXX
 port: 1521
 username: XXXX
 password: XXXX
 file: database-oracle-app-context.xml

spring:
   main:
     allow-bean-definition-overriding: true
 

